---
- name: Set system hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Preserve hostname across cloud-init reboots
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
    state: present

- name: Disable SWAP in runtime
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable SWAP persistently in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#\s]+\s+swap\s+.*)$'
    replace: '# \1'

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist kernel modules on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Enable IPv4 Packet Forwarding (sysctl)
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes

- name: Update APT cache and install prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - tar
    state: present
    update_cache: yes